// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public protocol SelectionSet: ApolloAPI.SelectionSet & ApolloAPI.RootSelectionSet
where Schema == GitHubAPI.SchemaMetadata {}

public protocol InlineFragment: ApolloAPI.SelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubAPI.SchemaMetadata {}

public protocol MutableSelectionSet: ApolloAPI.MutableRootSelectionSet
where Schema == GitHubAPI.SchemaMetadata {}

public protocol MutableInlineFragment: ApolloAPI.MutableSelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubAPI.SchemaMetadata {}

public enum SchemaMetadata: ApolloAPI.SchemaMetadata {
  public static let configuration: any ApolloAPI.SchemaConfiguration.Type = SchemaConfiguration.self

  public static func objectType(forTypename typename: String) -> ApolloAPI.Object? {
    switch typename {
    case "AddedToMergeQueueEvent": return GitHubAPI.Objects.AddedToMergeQueueEvent
    case "AddedToProjectEvent": return GitHubAPI.Objects.AddedToProjectEvent
    case "App": return GitHubAPI.Objects.App
    case "AssignedEvent": return GitHubAPI.Objects.AssignedEvent
    case "AutoMergeDisabledEvent": return GitHubAPI.Objects.AutoMergeDisabledEvent
    case "AutoMergeEnabledEvent": return GitHubAPI.Objects.AutoMergeEnabledEvent
    case "AutoRebaseEnabledEvent": return GitHubAPI.Objects.AutoRebaseEnabledEvent
    case "AutoSquashEnabledEvent": return GitHubAPI.Objects.AutoSquashEnabledEvent
    case "AutomaticBaseChangeFailedEvent": return GitHubAPI.Objects.AutomaticBaseChangeFailedEvent
    case "AutomaticBaseChangeSucceededEvent": return GitHubAPI.Objects.AutomaticBaseChangeSucceededEvent
    case "BaseRefChangedEvent": return GitHubAPI.Objects.BaseRefChangedEvent
    case "BaseRefDeletedEvent": return GitHubAPI.Objects.BaseRefDeletedEvent
    case "BaseRefForcePushedEvent": return GitHubAPI.Objects.BaseRefForcePushedEvent
    case "Blob": return GitHubAPI.Objects.Blob
    case "BlockedByAddedEvent": return GitHubAPI.Objects.BlockedByAddedEvent
    case "BlockedByRemovedEvent": return GitHubAPI.Objects.BlockedByRemovedEvent
    case "BlockingAddedEvent": return GitHubAPI.Objects.BlockingAddedEvent
    case "BlockingRemovedEvent": return GitHubAPI.Objects.BlockingRemovedEvent
    case "Bot": return GitHubAPI.Objects.Bot
    case "BranchProtectionRule": return GitHubAPI.Objects.BranchProtectionRule
    case "BypassForcePushAllowance": return GitHubAPI.Objects.BypassForcePushAllowance
    case "BypassPullRequestAllowance": return GitHubAPI.Objects.BypassPullRequestAllowance
    case "CWE": return GitHubAPI.Objects.CWE
    case "CheckRun": return GitHubAPI.Objects.CheckRun
    case "CheckSuite": return GitHubAPI.Objects.CheckSuite
    case "ClosedEvent": return GitHubAPI.Objects.ClosedEvent
    case "CodeOfConduct": return GitHubAPI.Objects.CodeOfConduct
    case "CommentDeletedEvent": return GitHubAPI.Objects.CommentDeletedEvent
    case "Commit": return GitHubAPI.Objects.Commit
    case "CommitComment": return GitHubAPI.Objects.CommitComment
    case "CommitCommentThread": return GitHubAPI.Objects.CommitCommentThread
    case "Comparison": return GitHubAPI.Objects.Comparison
    case "ConnectedEvent": return GitHubAPI.Objects.ConnectedEvent
    case "ConvertToDraftEvent": return GitHubAPI.Objects.ConvertToDraftEvent
    case "ConvertedNoteToIssueEvent": return GitHubAPI.Objects.ConvertedNoteToIssueEvent
    case "ConvertedToDiscussionEvent": return GitHubAPI.Objects.ConvertedToDiscussionEvent
    case "CrossReferencedEvent": return GitHubAPI.Objects.CrossReferencedEvent
    case "DemilestonedEvent": return GitHubAPI.Objects.DemilestonedEvent
    case "DependabotUpdate": return GitHubAPI.Objects.DependabotUpdate
    case "DependencyGraphManifest": return GitHubAPI.Objects.DependencyGraphManifest
    case "DeployKey": return GitHubAPI.Objects.DeployKey
    case "DeployedEvent": return GitHubAPI.Objects.DeployedEvent
    case "Deployment": return GitHubAPI.Objects.Deployment
    case "DeploymentEnvironmentChangedEvent": return GitHubAPI.Objects.DeploymentEnvironmentChangedEvent
    case "DeploymentReview": return GitHubAPI.Objects.DeploymentReview
    case "DeploymentStatus": return GitHubAPI.Objects.DeploymentStatus
    case "DisconnectedEvent": return GitHubAPI.Objects.DisconnectedEvent
    case "Discussion": return GitHubAPI.Objects.Discussion
    case "DiscussionCategory": return GitHubAPI.Objects.DiscussionCategory
    case "DiscussionComment": return GitHubAPI.Objects.DiscussionComment
    case "DiscussionPoll": return GitHubAPI.Objects.DiscussionPoll
    case "DiscussionPollOption": return GitHubAPI.Objects.DiscussionPollOption
    case "DraftIssue": return GitHubAPI.Objects.DraftIssue
    case "Enterprise": return GitHubAPI.Objects.Enterprise
    case "EnterpriseAdministratorInvitation": return GitHubAPI.Objects.EnterpriseAdministratorInvitation
    case "EnterpriseIdentityProvider": return GitHubAPI.Objects.EnterpriseIdentityProvider
    case "EnterpriseMemberInvitation": return GitHubAPI.Objects.EnterpriseMemberInvitation
    case "EnterpriseRepositoryInfo": return GitHubAPI.Objects.EnterpriseRepositoryInfo
    case "EnterpriseServerInstallation": return GitHubAPI.Objects.EnterpriseServerInstallation
    case "EnterpriseServerUserAccount": return GitHubAPI.Objects.EnterpriseServerUserAccount
    case "EnterpriseServerUserAccountEmail": return GitHubAPI.Objects.EnterpriseServerUserAccountEmail
    case "EnterpriseServerUserAccountsUpload": return GitHubAPI.Objects.EnterpriseServerUserAccountsUpload
    case "EnterpriseUserAccount": return GitHubAPI.Objects.EnterpriseUserAccount
    case "Environment": return GitHubAPI.Objects.Environment
    case "ExternalIdentity": return GitHubAPI.Objects.ExternalIdentity
    case "Gist": return GitHubAPI.Objects.Gist
    case "GistComment": return GitHubAPI.Objects.GistComment
    case "HeadRefDeletedEvent": return GitHubAPI.Objects.HeadRefDeletedEvent
    case "HeadRefForcePushedEvent": return GitHubAPI.Objects.HeadRefForcePushedEvent
    case "HeadRefRestoredEvent": return GitHubAPI.Objects.HeadRefRestoredEvent
    case "IpAllowListEntry": return GitHubAPI.Objects.IpAllowListEntry
    case "Issue": return GitHubAPI.Objects.Issue
    case "IssueComment": return GitHubAPI.Objects.IssueComment
    case "IssueType": return GitHubAPI.Objects.IssueType
    case "IssueTypeAddedEvent": return GitHubAPI.Objects.IssueTypeAddedEvent
    case "IssueTypeChangedEvent": return GitHubAPI.Objects.IssueTypeChangedEvent
    case "IssueTypeRemovedEvent": return GitHubAPI.Objects.IssueTypeRemovedEvent
    case "Label": return GitHubAPI.Objects.Label
    case "LabeledEvent": return GitHubAPI.Objects.LabeledEvent
    case "Language": return GitHubAPI.Objects.Language
    case "License": return GitHubAPI.Objects.License
    case "LinkedBranch": return GitHubAPI.Objects.LinkedBranch
    case "LockedEvent": return GitHubAPI.Objects.LockedEvent
    case "Mannequin": return GitHubAPI.Objects.Mannequin
    case "MarkedAsDuplicateEvent": return GitHubAPI.Objects.MarkedAsDuplicateEvent
    case "MarketplaceCategory": return GitHubAPI.Objects.MarketplaceCategory
    case "MarketplaceListing": return GitHubAPI.Objects.MarketplaceListing
    case "MemberFeatureRequestNotification": return GitHubAPI.Objects.MemberFeatureRequestNotification
    case "MembersCanDeleteReposClearAuditEntry": return GitHubAPI.Objects.MembersCanDeleteReposClearAuditEntry
    case "MembersCanDeleteReposDisableAuditEntry": return GitHubAPI.Objects.MembersCanDeleteReposDisableAuditEntry
    case "MembersCanDeleteReposEnableAuditEntry": return GitHubAPI.Objects.MembersCanDeleteReposEnableAuditEntry
    case "MentionedEvent": return GitHubAPI.Objects.MentionedEvent
    case "MergeQueue": return GitHubAPI.Objects.MergeQueue
    case "MergeQueueEntry": return GitHubAPI.Objects.MergeQueueEntry
    case "MergedEvent": return GitHubAPI.Objects.MergedEvent
    case "MigrationSource": return GitHubAPI.Objects.MigrationSource
    case "Milestone": return GitHubAPI.Objects.Milestone
    case "MilestonedEvent": return GitHubAPI.Objects.MilestonedEvent
    case "MovedColumnsInProjectEvent": return GitHubAPI.Objects.MovedColumnsInProjectEvent
    case "OIDCProvider": return GitHubAPI.Objects.OIDCProvider
    case "OauthApplicationCreateAuditEntry": return GitHubAPI.Objects.OauthApplicationCreateAuditEntry
    case "OrgAddBillingManagerAuditEntry": return GitHubAPI.Objects.OrgAddBillingManagerAuditEntry
    case "OrgAddMemberAuditEntry": return GitHubAPI.Objects.OrgAddMemberAuditEntry
    case "OrgBlockUserAuditEntry": return GitHubAPI.Objects.OrgBlockUserAuditEntry
    case "OrgConfigDisableCollaboratorsOnlyAuditEntry": return GitHubAPI.Objects.OrgConfigDisableCollaboratorsOnlyAuditEntry
    case "OrgConfigEnableCollaboratorsOnlyAuditEntry": return GitHubAPI.Objects.OrgConfigEnableCollaboratorsOnlyAuditEntry
    case "OrgCreateAuditEntry": return GitHubAPI.Objects.OrgCreateAuditEntry
    case "OrgDisableOauthAppRestrictionsAuditEntry": return GitHubAPI.Objects.OrgDisableOauthAppRestrictionsAuditEntry
    case "OrgDisableSamlAuditEntry": return GitHubAPI.Objects.OrgDisableSamlAuditEntry
    case "OrgDisableTwoFactorRequirementAuditEntry": return GitHubAPI.Objects.OrgDisableTwoFactorRequirementAuditEntry
    case "OrgEnableOauthAppRestrictionsAuditEntry": return GitHubAPI.Objects.OrgEnableOauthAppRestrictionsAuditEntry
    case "OrgEnableSamlAuditEntry": return GitHubAPI.Objects.OrgEnableSamlAuditEntry
    case "OrgEnableTwoFactorRequirementAuditEntry": return GitHubAPI.Objects.OrgEnableTwoFactorRequirementAuditEntry
    case "OrgInviteMemberAuditEntry": return GitHubAPI.Objects.OrgInviteMemberAuditEntry
    case "OrgInviteToBusinessAuditEntry": return GitHubAPI.Objects.OrgInviteToBusinessAuditEntry
    case "OrgOauthAppAccessApprovedAuditEntry": return GitHubAPI.Objects.OrgOauthAppAccessApprovedAuditEntry
    case "OrgOauthAppAccessBlockedAuditEntry": return GitHubAPI.Objects.OrgOauthAppAccessBlockedAuditEntry
    case "OrgOauthAppAccessDeniedAuditEntry": return GitHubAPI.Objects.OrgOauthAppAccessDeniedAuditEntry
    case "OrgOauthAppAccessRequestedAuditEntry": return GitHubAPI.Objects.OrgOauthAppAccessRequestedAuditEntry
    case "OrgOauthAppAccessUnblockedAuditEntry": return GitHubAPI.Objects.OrgOauthAppAccessUnblockedAuditEntry
    case "OrgRemoveBillingManagerAuditEntry": return GitHubAPI.Objects.OrgRemoveBillingManagerAuditEntry
    case "OrgRemoveMemberAuditEntry": return GitHubAPI.Objects.OrgRemoveMemberAuditEntry
    case "OrgRemoveOutsideCollaboratorAuditEntry": return GitHubAPI.Objects.OrgRemoveOutsideCollaboratorAuditEntry
    case "OrgRestoreMemberAuditEntry": return GitHubAPI.Objects.OrgRestoreMemberAuditEntry
    case "OrgRestoreMemberMembershipOrganizationAuditEntryData": return GitHubAPI.Objects.OrgRestoreMemberMembershipOrganizationAuditEntryData
    case "OrgRestoreMemberMembershipRepositoryAuditEntryData": return GitHubAPI.Objects.OrgRestoreMemberMembershipRepositoryAuditEntryData
    case "OrgRestoreMemberMembershipTeamAuditEntryData": return GitHubAPI.Objects.OrgRestoreMemberMembershipTeamAuditEntryData
    case "OrgUnblockUserAuditEntry": return GitHubAPI.Objects.OrgUnblockUserAuditEntry
    case "OrgUpdateDefaultRepositoryPermissionAuditEntry": return GitHubAPI.Objects.OrgUpdateDefaultRepositoryPermissionAuditEntry
    case "OrgUpdateMemberAuditEntry": return GitHubAPI.Objects.OrgUpdateMemberAuditEntry
    case "OrgUpdateMemberRepositoryCreationPermissionAuditEntry": return GitHubAPI.Objects.OrgUpdateMemberRepositoryCreationPermissionAuditEntry
    case "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry": return GitHubAPI.Objects.OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
    case "Organization": return GitHubAPI.Objects.Organization
    case "OrganizationIdentityProvider": return GitHubAPI.Objects.OrganizationIdentityProvider
    case "OrganizationInvitation": return GitHubAPI.Objects.OrganizationInvitation
    case "OrganizationMemberConnection": return GitHubAPI.Objects.OrganizationMemberConnection
    case "OrganizationMigration": return GitHubAPI.Objects.OrganizationMigration
    case "Package": return GitHubAPI.Objects.Package
    case "PackageFile": return GitHubAPI.Objects.PackageFile
    case "PackageTag": return GitHubAPI.Objects.PackageTag
    case "PackageVersion": return GitHubAPI.Objects.PackageVersion
    case "ParentIssueAddedEvent": return GitHubAPI.Objects.ParentIssueAddedEvent
    case "ParentIssueRemovedEvent": return GitHubAPI.Objects.ParentIssueRemovedEvent
    case "PinnedDiscussion": return GitHubAPI.Objects.PinnedDiscussion
    case "PinnedEnvironment": return GitHubAPI.Objects.PinnedEnvironment
    case "PinnedEvent": return GitHubAPI.Objects.PinnedEvent
    case "PinnedIssue": return GitHubAPI.Objects.PinnedIssue
    case "PrivateRepositoryForkingDisableAuditEntry": return GitHubAPI.Objects.PrivateRepositoryForkingDisableAuditEntry
    case "PrivateRepositoryForkingEnableAuditEntry": return GitHubAPI.Objects.PrivateRepositoryForkingEnableAuditEntry
    case "Project": return GitHubAPI.Objects.Project
    case "ProjectCard": return GitHubAPI.Objects.ProjectCard
    case "ProjectColumn": return GitHubAPI.Objects.ProjectColumn
    case "ProjectV2": return GitHubAPI.Objects.ProjectV2
    case "ProjectV2Field": return GitHubAPI.Objects.ProjectV2Field
    case "ProjectV2Item": return GitHubAPI.Objects.ProjectV2Item
    case "ProjectV2ItemFieldDateValue": return GitHubAPI.Objects.ProjectV2ItemFieldDateValue
    case "ProjectV2ItemFieldIterationValue": return GitHubAPI.Objects.ProjectV2ItemFieldIterationValue
    case "ProjectV2ItemFieldNumberValue": return GitHubAPI.Objects.ProjectV2ItemFieldNumberValue
    case "ProjectV2ItemFieldSingleSelectValue": return GitHubAPI.Objects.ProjectV2ItemFieldSingleSelectValue
    case "ProjectV2ItemFieldTextValue": return GitHubAPI.Objects.ProjectV2ItemFieldTextValue
    case "ProjectV2IterationField": return GitHubAPI.Objects.ProjectV2IterationField
    case "ProjectV2SingleSelectField": return GitHubAPI.Objects.ProjectV2SingleSelectField
    case "ProjectV2StatusUpdate": return GitHubAPI.Objects.ProjectV2StatusUpdate
    case "ProjectV2View": return GitHubAPI.Objects.ProjectV2View
    case "ProjectV2Workflow": return GitHubAPI.Objects.ProjectV2Workflow
    case "PublicKey": return GitHubAPI.Objects.PublicKey
    case "PullRequest": return GitHubAPI.Objects.PullRequest
    case "PullRequestCommit": return GitHubAPI.Objects.PullRequestCommit
    case "PullRequestCommitCommentThread": return GitHubAPI.Objects.PullRequestCommitCommentThread
    case "PullRequestReview": return GitHubAPI.Objects.PullRequestReview
    case "PullRequestReviewComment": return GitHubAPI.Objects.PullRequestReviewComment
    case "PullRequestReviewThread": return GitHubAPI.Objects.PullRequestReviewThread
    case "PullRequestThread": return GitHubAPI.Objects.PullRequestThread
    case "Push": return GitHubAPI.Objects.Push
    case "PushAllowance": return GitHubAPI.Objects.PushAllowance
    case "Query": return GitHubAPI.Objects.Query
    case "RateLimit": return GitHubAPI.Objects.RateLimit
    case "Reaction": return GitHubAPI.Objects.Reaction
    case "ReadyForReviewEvent": return GitHubAPI.Objects.ReadyForReviewEvent
    case "Ref": return GitHubAPI.Objects.Ref
    case "ReferencedEvent": return GitHubAPI.Objects.ReferencedEvent
    case "Release": return GitHubAPI.Objects.Release
    case "ReleaseAsset": return GitHubAPI.Objects.ReleaseAsset
    case "RemovedFromMergeQueueEvent": return GitHubAPI.Objects.RemovedFromMergeQueueEvent
    case "RemovedFromProjectEvent": return GitHubAPI.Objects.RemovedFromProjectEvent
    case "RenamedTitleEvent": return GitHubAPI.Objects.RenamedTitleEvent
    case "ReopenedEvent": return GitHubAPI.Objects.ReopenedEvent
    case "RepoAccessAuditEntry": return GitHubAPI.Objects.RepoAccessAuditEntry
    case "RepoAddMemberAuditEntry": return GitHubAPI.Objects.RepoAddMemberAuditEntry
    case "RepoAddTopicAuditEntry": return GitHubAPI.Objects.RepoAddTopicAuditEntry
    case "RepoArchivedAuditEntry": return GitHubAPI.Objects.RepoArchivedAuditEntry
    case "RepoChangeMergeSettingAuditEntry": return GitHubAPI.Objects.RepoChangeMergeSettingAuditEntry
    case "RepoConfigDisableAnonymousGitAccessAuditEntry": return GitHubAPI.Objects.RepoConfigDisableAnonymousGitAccessAuditEntry
    case "RepoConfigDisableCollaboratorsOnlyAuditEntry": return GitHubAPI.Objects.RepoConfigDisableCollaboratorsOnlyAuditEntry
    case "RepoConfigDisableContributorsOnlyAuditEntry": return GitHubAPI.Objects.RepoConfigDisableContributorsOnlyAuditEntry
    case "RepoConfigDisableSockpuppetDisallowedAuditEntry": return GitHubAPI.Objects.RepoConfigDisableSockpuppetDisallowedAuditEntry
    case "RepoConfigEnableAnonymousGitAccessAuditEntry": return GitHubAPI.Objects.RepoConfigEnableAnonymousGitAccessAuditEntry
    case "RepoConfigEnableCollaboratorsOnlyAuditEntry": return GitHubAPI.Objects.RepoConfigEnableCollaboratorsOnlyAuditEntry
    case "RepoConfigEnableContributorsOnlyAuditEntry": return GitHubAPI.Objects.RepoConfigEnableContributorsOnlyAuditEntry
    case "RepoConfigEnableSockpuppetDisallowedAuditEntry": return GitHubAPI.Objects.RepoConfigEnableSockpuppetDisallowedAuditEntry
    case "RepoConfigLockAnonymousGitAccessAuditEntry": return GitHubAPI.Objects.RepoConfigLockAnonymousGitAccessAuditEntry
    case "RepoConfigUnlockAnonymousGitAccessAuditEntry": return GitHubAPI.Objects.RepoConfigUnlockAnonymousGitAccessAuditEntry
    case "RepoCreateAuditEntry": return GitHubAPI.Objects.RepoCreateAuditEntry
    case "RepoDestroyAuditEntry": return GitHubAPI.Objects.RepoDestroyAuditEntry
    case "RepoRemoveMemberAuditEntry": return GitHubAPI.Objects.RepoRemoveMemberAuditEntry
    case "RepoRemoveTopicAuditEntry": return GitHubAPI.Objects.RepoRemoveTopicAuditEntry
    case "Repository": return GitHubAPI.Objects.Repository
    case "RepositoryConnection": return GitHubAPI.Objects.RepositoryConnection
    case "RepositoryInvitation": return GitHubAPI.Objects.RepositoryInvitation
    case "RepositoryMigration": return GitHubAPI.Objects.RepositoryMigration
    case "RepositoryRule": return GitHubAPI.Objects.RepositoryRule
    case "RepositoryRuleset": return GitHubAPI.Objects.RepositoryRuleset
    case "RepositoryRulesetBypassActor": return GitHubAPI.Objects.RepositoryRulesetBypassActor
    case "RepositoryTopic": return GitHubAPI.Objects.RepositoryTopic
    case "RepositoryVisibilityChangeDisableAuditEntry": return GitHubAPI.Objects.RepositoryVisibilityChangeDisableAuditEntry
    case "RepositoryVisibilityChangeEnableAuditEntry": return GitHubAPI.Objects.RepositoryVisibilityChangeEnableAuditEntry
    case "RepositoryVulnerabilityAlert": return GitHubAPI.Objects.RepositoryVulnerabilityAlert
    case "ReviewDismissalAllowance": return GitHubAPI.Objects.ReviewDismissalAllowance
    case "ReviewDismissedEvent": return GitHubAPI.Objects.ReviewDismissedEvent
    case "ReviewRequest": return GitHubAPI.Objects.ReviewRequest
    case "ReviewRequestRemovedEvent": return GitHubAPI.Objects.ReviewRequestRemovedEvent
    case "ReviewRequestedEvent": return GitHubAPI.Objects.ReviewRequestedEvent
    case "SavedReply": return GitHubAPI.Objects.SavedReply
    case "SearchResultItemConnection": return GitHubAPI.Objects.SearchResultItemConnection
    case "SecurityAdvisory": return GitHubAPI.Objects.SecurityAdvisory
    case "SponsorsActivity": return GitHubAPI.Objects.SponsorsActivity
    case "SponsorsListing": return GitHubAPI.Objects.SponsorsListing
    case "SponsorsListingFeaturedItem": return GitHubAPI.Objects.SponsorsListingFeaturedItem
    case "SponsorsTier": return GitHubAPI.Objects.SponsorsTier
    case "Sponsorship": return GitHubAPI.Objects.Sponsorship
    case "SponsorshipNewsletter": return GitHubAPI.Objects.SponsorshipNewsletter
    case "StargazerConnection": return GitHubAPI.Objects.StargazerConnection
    case "Status": return GitHubAPI.Objects.Status
    case "StatusCheckRollup": return GitHubAPI.Objects.StatusCheckRollup
    case "StatusContext": return GitHubAPI.Objects.StatusContext
    case "SubIssueAddedEvent": return GitHubAPI.Objects.SubIssueAddedEvent
    case "SubIssueRemovedEvent": return GitHubAPI.Objects.SubIssueRemovedEvent
    case "SubscribedEvent": return GitHubAPI.Objects.SubscribedEvent
    case "Tag": return GitHubAPI.Objects.Tag
    case "Team": return GitHubAPI.Objects.Team
    case "TeamAddMemberAuditEntry": return GitHubAPI.Objects.TeamAddMemberAuditEntry
    case "TeamAddRepositoryAuditEntry": return GitHubAPI.Objects.TeamAddRepositoryAuditEntry
    case "TeamChangeParentTeamAuditEntry": return GitHubAPI.Objects.TeamChangeParentTeamAuditEntry
    case "TeamDiscussion": return GitHubAPI.Objects.TeamDiscussion
    case "TeamDiscussionComment": return GitHubAPI.Objects.TeamDiscussionComment
    case "TeamRemoveMemberAuditEntry": return GitHubAPI.Objects.TeamRemoveMemberAuditEntry
    case "TeamRemoveRepositoryAuditEntry": return GitHubAPI.Objects.TeamRemoveRepositoryAuditEntry
    case "Topic": return GitHubAPI.Objects.Topic
    case "TransferredEvent": return GitHubAPI.Objects.TransferredEvent
    case "Tree": return GitHubAPI.Objects.Tree
    case "UnassignedEvent": return GitHubAPI.Objects.UnassignedEvent
    case "UnlabeledEvent": return GitHubAPI.Objects.UnlabeledEvent
    case "UnlockedEvent": return GitHubAPI.Objects.UnlockedEvent
    case "UnmarkedAsDuplicateEvent": return GitHubAPI.Objects.UnmarkedAsDuplicateEvent
    case "UnpinnedEvent": return GitHubAPI.Objects.UnpinnedEvent
    case "UnsubscribedEvent": return GitHubAPI.Objects.UnsubscribedEvent
    case "User": return GitHubAPI.Objects.User
    case "UserBlockedEvent": return GitHubAPI.Objects.UserBlockedEvent
    case "UserConnection": return GitHubAPI.Objects.UserConnection
    case "UserContentEdit": return GitHubAPI.Objects.UserContentEdit
    case "UserList": return GitHubAPI.Objects.UserList
    case "UserNamespaceRepository": return GitHubAPI.Objects.UserNamespaceRepository
    case "UserStatus": return GitHubAPI.Objects.UserStatus
    case "VerifiableDomain": return GitHubAPI.Objects.VerifiableDomain
    case "Workflow": return GitHubAPI.Objects.Workflow
    case "WorkflowRun": return GitHubAPI.Objects.WorkflowRun
    case "WorkflowRunFile": return GitHubAPI.Objects.WorkflowRunFile
    default: return nil
    }
  }
}

public enum Objects {}
public enum Interfaces {}
public enum Unions {}
